# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# Change these first
owner: hst1189 # GitHub username
repo: upptime  # GitHub repository name

skipDescriptionUpdate: true
skipTopicsUpdate: true
#skipHomepageUpdate: true


sites:
  - name: www.grapehut.us.kg
    url: https://www.grapehut.us.kg/
    icon: https://github.githubassets.com/favicons/favicon.svg
  
  - name: www.grapehut.us.kg/gmerss
    url: https://www.grapehut.us.kg/gmerss/
    icon: https://github.githubassets.com/favicons/favicon.svg
  
  - name: www.grapehut.us.kg/webstack
    url: https://www.grapehut.us.kg/webstack/
    icon: https://github.githubassets.com/favicons/favicon.svg
  
  - name: www.grapehut.us.kg/live2d-widget
    url: https://www.grapehut.us.kg/live2d-widget/
    icon: https://www.grapehut.us.kg/live2d-widget/avatar.png
    
  - name: miraitech-chiyoda.com
    url: https://miraitech-chiyoda.com/
    icon: https://miraitech-chiyoda.com/img/favicon.ico
  
    
status-website:
  # Add your custom domain name, or baseUrl
  baseUrl: /upptime
  
  # Status website title
  name:
  # Status website logo
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: 
  introMessage:
  theme: light
  
  navbar:
    - title: Home
      href: /upptime

i18n:
  footer: Copyright © 2024 小饅頭の部屋 All Rights Reserved.
  url: 网站
  status: 状态
  history: 记录
  responseTime: 响应时间
  uptime: 正常运行率
  up: "🟩 正常"
  degraded: "🟨 延时"
  down: "🟥 宕机"




